services:
  - type: web
    name: discord-revolt-bridge
    env: node
    buildCommand: npm install && npm run build
    startCommand: ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: REVOLT_TOKEN
        sync: false
